### Primary and Secondary Analysis

In [ ]:
import pandas as pd

In [ ]:
city_target_passenger_rating_df = pd.read_csv('city_target_passenger_rating.csv')
city_target_passenger_rating_df.head()

  city_id  target_avg_passenger_rating
0    CH01                         8.00
1    UP01                         7.25
2    AP01                         8.50
3    MP01                         8.00
4    RJ01                         8.25

In [ ]:
dim_city_df = pd.read_csv('dim_city.csv')
dim_city_df.head()

  city_id city_name
0    RJ01    Jaipur
1    UP01   Lucknow
2    GJ01     Surat
3    KL01     Kochi
4    MP01    Indore

In [ ]:
dim_date_df = pd.read_csv('dim_date.csv')
dim_date_df.head()

         date start_of_month month_name day_type
0  2024-01-01     2024-01-01    January  Weekday
1  2024-01-02     2024-01-01    January  Weekday
2  2024-01-03     2024-01-01    January  Weekday
3  2024-01-04     2024-01-01    January  Weekday
4  2024-01-05     2024-01-01    January  Weekday

In [ ]:
dim_repeat_trip_distribution_df = pd.read_csv('dim_repeat_trip_distribution.csv')
dim_repeat_trip_distribution_df.head()

        month city_id trip_count  repeat_passenger_count
0  2024-01-01    AP01   10-Trips                       7
1  2024-01-01    AP01    2-Trips                     352
2  2024-01-01    AP01    3-Trips                     158
3  2024-01-01    AP01    4-Trips                      53
4  2024-01-01    AP01    5-Trips                      38

In [ ]:
fact_passenger_summary_df = pd.read_csv('fact_passenger_summary.csv')
fact_passenger_summary_df.head(10)

        month city_id  new_passengers  repeat_passengers  total_passengers
0  2024-01-01    AP01            2513                650              3163
1  2024-01-01    CH01            3920                720              4640
2  2024-01-01    GJ01            2432               1184              3616
3  2024-01-01    GJ02            2089                544              2633
4  2024-01-01    KA01            1957                172              2129
5  2024-01-01    KL01            4865                795              5660
6  2024-01-01    MP01            2843               1033              3876
7  2024-01-01    RJ01           10423               1422             11845
8  2024-01-01    TN01            1822                392              2214
9  2024-01-01    UP01            3465               1431              4896

In [ ]:
fact_trips_df = pd.read_csv('fact_trips.csv')
fact_trips_df.head()

,trip_id,date,city_id,passenger_type,distance_travelled(km),fare_amount,passenger_rating,driver_rating
0,TRPLUC240113d55de2fb,2024-01-13,UP01,repeated,11,158,5,5
1,TRPVAD240129a3b6dba8,2024-01-29,GJ02,repeated,7,74,5,5
2,TRPCOI240107a42430fb,2024-01-07,TN01,repeated,11,155,8,8
3,TRPKOC240325d7601389,2024-03-25,KL01,repeated,36,427,9,10
4,TRPVIS2406027be97166,2024-06-02,AP01,new,17,265,8,8

In [ ]:
monthly_target_new_passengers_df = pd.read_csv('monthly_target_new_passengers.csv')
monthly_target_new_passengers_df.head()

        month city_id  target_new_passengers
0  2024-05-01    GJ01                   1500
1  2024-05-01    GJ02                   1500
2  2024-03-01    GJ01                   2000
3  2024-05-01    UP01                   2000
4  2024-05-01    MP01                   2000

In [ ]:
monthly_target_trips_df = pd.read_csv('monthly_target_trips.csv')
monthly_target_trips_df.head()

        month city_id  total_target_trips
0  2024-03-01    MP01                7000
1  2024-05-01    KA01                2500
2  2024-04-01    UP01               11000
3  2024-02-01    GJ02                6000
4  2024-05-01    KL01                9000

### 1. Top and Bottom Performing Cities:

*   Indentify the top 3 and bottom 3 cities by total trips over the entire analysis period.

In [ ]:
trips_by_city = fact_trips_df.groupby('city_id')['trip_id'].count().reset_index()

# Calculate total trips per city
city_trip_counts = fact_trips_df.groupby('city_id')['trip_id'].count().reset_index()
city_trip_counts.columns = ['city_id', 'total_trips']

# Top and Bottom 3 cities
top_3 = city_trip_counts.nlargest(3, 'total_trips')
bottom_3 = city_trip_counts.nsmallest(3, 'total_trips')

print("Top 3 Cities:")
print(top_3)

print("\nBottom 3 Cities:")
print(bottom_3)

Top 3 Cities:
  city_id  total_trips
7    RJ01        76888
9    UP01        64299
2    GJ01        54843

Bottom 3 Cities:
  city_id  total_trips
4    KA01        16238
8    TN01        21104
0    AP01        28366

### 2. Average Fare per Trip by City


*   Calculate the average fare per trip for each city and compare it with the city's average trip distance. Identify the cities with the highest and lowest average fare per trip to assess pricing efficiency across locations.

In [ ]:
# Calculate average fare per trip
avg_fare_per_trip = fact_trips_df.groupby('city_id')['fare_amount'].mean().reset_index()
avg_fare_per_trip.columns = ['city_id', 'avg_fare_per_trip']

# Cities with highest and lowest average fare per trip
highest_avg_fare = avg_fare_per_trip.nlargest(3, 'avg_fare_per_trip')
lowest_avg_fare = avg_fare_per_trip.nsmallest(3, 'avg_fare_per_trip')

print("Cities with Highest Average Fare per Trip:")
print(highest_avg_fare)

print("\nCities with Lowest Average Fare per Trip:")
print(lowest_avg_fare)

Cities with Highest Average Fare per Trip:
  city_id  avg_fare_per_trip
7    RJ01         483.918128
5    KL01         335.245079
1    CH01         283.686950

Cities with Lowest Average Fare per Trip:
  city_id  avg_fare_per_trip
2    GJ01         117.272925
3    GJ02         118.566165
9    UP01         147.180376

### 3. Average Ratings by City and Passenger Type


*   Calculate the average passenger and driver ratings for each city, segmented by passenger type (new vs. repeat). Identify cities with the highest and lowest average ratings.

In [ ]:
# Grouping by city_id and passenger_type to calculate average ratings
average_ratings = fact_trips_df.groupby(["city_id", "passenger_type"])[
    ["passenger_rating", "driver_rating"]
].mean().reset_index()

# Cities with the highest and lowest average passenger ratings
highest_passenger_rating_city = average_ratings.loc[
    average_ratings["passenger_rating"].idxmax()
]
lowest_passenger_rating_city = average_ratings.loc[
    average_ratings["passenger_rating"].idxmin()
]

# Cities with the highest and lowest average driver ratings
highest_driver_rating_city = average_ratings.loc[
    average_ratings["driver_rating"].idxmax()
]
lowest_driver_rating_city = average_ratings.loc[
    average_ratings["driver_rating"].idxmin()
]

# Displaying the results
print("Average Ratings by City and Passenger Type:")
print(average_ratings)
print("\nCity with Highest Passenger Rating:")
print(highest_passenger_rating_city)
print("\nCity with Lowest Passenger Rating:")
print(lowest_passenger_rating_city)
print("\nCity with Highest Driver Rating:")
print(highest_driver_rating_city)
print("\nCity with Lowest Driver Rating:")
print(lowest_driver_rating_city)

Average Ratings by City and Passenger Type:
   city_id passenger_type  passenger_rating  driver_rating
0     AP01            new          8.976151       8.979995
1     AP01       repeated          7.989628       8.992701
2     CH01            new          8.489158       7.992120
3     CH01       repeated          7.493798       7.472824
4     GJ01            new          7.984173       6.994925
5     GJ01       repeated          5.995511       6.479441
6     GJ02            new          7.979263       7.004147
7     GJ02       repeated          5.978629       6.481072
8     KA01            new          8.982964       8.982878
9     KA01       repeated          7.978495       8.965767
10    KL01            new          8.987394       8.985350
11    KL01       repeated          8.003665       8.989830
12    MP01            new          8.485837       7.970800
13    MP01       repeated          7.473961       7.477404
14    RJ01            new          8.985018       8.988246
15    RJ01       repeated          7.991042       8.984790
16    TN01            new          8.485788       7.990604
17    TN01       repeated          7.475457       7.480778
18    UP01            new          7.977429       6.990406
19    UP01       repeated          5.985741       6.491663

City with Highest Passenger Rating:
city_id                 KL01
passenger_type           new
passenger_rating    8.987394
driver_rating        8.98535
Name: 10, dtype: object

City with Lowest Passenger Rating:
city_id                 GJ02
passenger_type      repeated
passenger_rating    5.978629
driver_rating       6.481072
Name: 7, dtype: object

City with Highest Driver Rating:
city_id                 AP01
passenger_type      repeated
passenger_rating    7.989628
driver_rating       8.992701
Name: 1, dtype: object

City with Lowest Driver Rating:
city_id                 GJ01
passenger_type      repeated
passenger_rating    5.995511
driver_rating       6.479441
Name: 5, dtype: object

### 4. Peak and Low Demand Months by City


*   For each city, identify the month with the highest total trips (peak demand) and the month with the lowest total trips (low demand). This analysis will help Goodcabs understand seasonal patterns and adjust recources accordingly.

In [ ]:
# Extract the month from the date column
fact_trips_df["month"] = pd.to_datetime(fact_trips_df["date"]).dt.to_period("M")

# Group by city and month to calculate total trips
monthly_trip_counts = fact_trips_df.groupby(["city_id", "month"]).size().reset_index(name="total_trips")

# Identify the peak and low-demand months for each city
peak_demand_months = monthly_trip_counts.loc[monthly_trip_counts.groupby("city_id")["total_trips"].idxmax()]
low_demand_months = monthly_trip_counts.loc[monthly_trip_counts.groupby("city_id")["total_trips"].idxmin()]

# Display the results
print("Peak Demand Months by City:")
print(peak_demand_months)
print("\nLow Demand Months by City:")
print(low_demand_months)

Peak Demand Months by City:
   city_id    month  total_trips
3     AP01  2024-04         4938
7     CH01  2024-02         7387
15    GJ01  2024-04         9831
21    GJ02  2024-04         5941
28    KA01  2024-05         3007
34    KL01  2024-05        10014
40    MP01  2024-05         7787
43    RJ01  2024-02        15872
50    TN01  2024-03         3680
55    UP01  2024-02        12060

Low Demand Months by City:
   city_id    month  total_trips
0     AP01  2024-01         4468
9     CH01  2024-04         5566
12    GJ01  2024-01         8358
23    GJ02  2024-06         4685
24    KA01  2024-01         2485
35    KL01  2024-06         6399
41    MP01  2024-06         6288
47    RJ01  2024-06         9842
53    TN01  2024-06         3158
58    UP01  2024-05         9705

### 5. Weekend vs. Weekday Trip Demand by City


*   Compare the total trips taken on weekdays versus weekends for each city over the six-month period. Identify cities with a strong preference for either weekend or weekday trips to understand demand variations.

In [ ]:
# Merge fact_trips with dim_date to get day_type (weekday/weekend)
fact_trips = pd.merge(fact_trips_df, dim_date_df[["date", "day_type"]], on="date", how="left")

# Group by city_id and day_type to calculate total trips
trip_demand_by_day_type = fact_trips.groupby(["city_id", "day_type"]).size().reset_index(name="total_trips")

# Pivot the table to have separate columns for weekday and weekend trips
trip_demand_pivot = trip_demand_by_day_type.pivot(index="city_id", columns="day_type", values="total_trips").reset_index()

# Rename columns for clarity (ensure day_type values are "weekday" and "weekend")
trip_demand_pivot.columns = ["city_id", "weekday_trips", "weekend_trips"]

# Fill NaN values with 0 in case some cities have no trips for a day type
trip_demand_pivot.fillna(0, inplace=True)

# Calculate the preference (difference between weekday and weekend trips)
trip_demand_pivot["preference"] = trip_demand_pivot["weekday_trips"] - trip_demand_pivot["weekend_trips"]

# Identify cities with strong preferences
strong_weekday_cities = trip_demand_pivot[trip_demand_pivot["preference"] > 0]
strong_weekend_cities = trip_demand_pivot[trip_demand_pivot["preference"] < 0]

# Display results
print("Trip Demand by Day Type (Weekday vs. Weekend):")
print(trip_demand_pivot)
print("\nCities with Strong Preference for Weekday Trips:")
print(strong_weekday_cities)
print("\nCities with Strong Preference for Weekend Trips:")
print(strong_weekend_cities)

Trip Demand by Day Type (Weekday vs. Weekend):
  city_id  weekday_trips  weekend_trips  preference
0    AP01          15100          13266        1834
1    CH01          19914          19067         847
2    GJ01          37793          17050       20743
3    GJ02          20310          11716        8594
4    KA01           6424           9814       -3390
5    KL01          22915          27787       -4872
6    MP01          21198          21258         -60
7    RJ01          32491          44397      -11906
8    TN01          12576           8528        4048
9    UP01          49617          14682       34935

Cities with Strong Preference for Weekday Trips:
  city_id  weekday_trips  weekend_trips  preference
0    AP01          15100          13266        1834
1    CH01          19914          19067         847
2    GJ01          37793          17050       20743
3    GJ02          20310          11716        8594
8    TN01          12576           8528        4048
9    UP01          49617          14682       34935

Cities with Strong Preference for Weekend Trips:
  city_id  weekday_trips  weekend_trips  preference
4    KA01           6424           9814       -3390
5    KL01          22915          27787       -4872
6    MP01          21198          21258         -60
7    RJ01          32491          44397      -11906

### 6. Repeat Passenger Frequency and City Contribution Analysis


*   Analyse the frequency of trips taken by repeat passengers in each city (e.g., % of repeat passengers taking 2 trips, 3 trips, etc.). Indentify which cities contribute most to higher trip frequencies among repeat passengers, and examine if there are distinguishable patterns between tourism-focused and business-focused cities.

In [ ]:
# Calculate total repeat passengers by city
city_total_repeat_passengers = (
    dim_repeat_trip_distribution_df.groupby("city_id")["repeat_passenger_count"].sum().reset_index()
)
city_total_repeat_passengers.rename(columns={"repeat_passenger_count": "total_repeat_passengers"}, inplace=True)

# Merge total repeat passengers back with the original data
repeat_trip_distribution = pd.merge(
    dim_repeat_trip_distribution_df,
    city_total_repeat_passengers,
    on="city_id",
    how="left"
)

# Calculate percentage contribution for each trip frequency
repeat_trip_distribution["percentage_contribution"] = (
    repeat_trip_distribution["repeat_passenger_count"] / repeat_trip_distribution["total_repeat_passengers"] * 100
)

# Identify cities contributing most to higher trip frequencies
# Assuming "higher trip frequencies" means repeat passengers with 5+ trips
high_trip_frequencies = repeat_trip_distribution[
    repeat_trip_distribution["trip_count"].apply(lambda x: int(x.split("-")[0]) >= 5)
]
city_high_trip_contributions = (
    high_trip_frequencies.groupby("city_id")["repeat_passenger_count"].sum().reset_index()
)
city_high_trip_contributions.rename(columns={"repeat_passenger_count": "high_trip_contributions"}, inplace=True)

# Merge city high trip contributions back with total passengers for comparison
city_analysis = pd.merge(
    city_total_repeat_passengers,
    city_high_trip_contributions,
    on="city_id",
    how="left"
)

# Fill NaN values in high_trip_contributions with 0
city_analysis["high_trip_contributions"].fillna(0, inplace=True)

# Add a percentage column for high trip contributions
city_analysis["high_trip_percentage"] = (
    city_analysis["high_trip_contributions"] / city_analysis["total_repeat_passengers"] * 100
)

# Sort cities by high trip percentage
city_analysis = city_analysis.sort_values("high_trip_percentage", ascending=False)

# Display results
print("Repeat Passenger Frequency Contribution by City:")
print(repeat_trip_distribution)
print("\nCity Contribution to High Trip Frequencies:")
print(city_analysis)

# For tourism vs. business analysis, you would need a separate city classification table
# You can analyze patterns by merging with that classification and visualizing trends

Repeat Passenger Frequency Contribution by City:
          month city_id trip_count  repeat_passenger_count  \
0    2024-01-01    AP01   10-Trips                       7
1    2024-01-01    AP01    2-Trips                     352
2    2024-01-01    AP01    3-Trips                     158
3    2024-01-01    AP01    4-Trips                      53
4    2024-01-01    AP01    5-Trips                      38
..          ...     ...        ...                     ...
535  2024-06-01    UP01    5-Trips                     272
536  2024-06-01    UP01    6-Trips                     272
537  2024-06-01    UP01    7-Trips                     246
538  2024-06-01    UP01    8-Trips                      83
539  2024-06-01    UP01    9-Trips                      19

     total_repeat_passengers  percentage_contribution
0                       5108                 0.137040
1                       5108                 6.891151
2                       5108                 3.093187
3                       5108                 1.037588
4                       5108                 0.743931
..                       ...                      ...
535                     9597                 2.834219
536                     9597                 2.834219
537                     9597                 2.563301
538                     9597                 0.864854
539                     9597                 0.197979

[540 rows x 6 columns]

City Contribution to High Trip Frequencies:
  city_id  total_repeat_passengers  high_trip_contributions  \
3    GJ02                     4346                     2583
2    GJ01                     8638                     5133
9    UP01                     9597                     5698
8    TN01                     2551                     1490
1    CH01                     5070                     1658
6    MP01                     7216                     2134
7    RJ01                     9682                     1647
5    KL01                     7626                     1233
4    KA01                     1477                      208
0    AP01                     5108                      705

   high_trip_percentage
3             59.433962
2             59.423478
9             59.372721
8             58.408467
1             32.702170
6             29.573171
7             17.010948
5             16.168371
4             14.082600
0             13.801879

<ipython-input-22-c821f42dd5e9>:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  city_analysis["high_trip_contributions"].fillna(0, inplace=True)

### 7. Monthly Target Achievement Analysis for Key Metrics


*   For each city, evaluate monthly performance against targets for total trips, new passengers, and average passenger ratings from targets_db. Determine if each metric met, exceeded, or missed the target, and calculate the percentage difference. Identify any consistent patterns in target achievevement, particularly across tourism versus business - focused cities.

In [ ]:
# Calculate average distance and one-time passenger proportions
city_analysis = fact_trips_df.groupby("city_id").agg(
    avg_distance=("distance_travelled(km)", "mean"),
    total_trips=("trip_id", "count"),
    one_time_passengers=("passenger_type", lambda x: (x == "new").sum())
).reset_index()

# Calculate the proportion of one-time passengers
city_analysis["one_time_passenger_ratio"] = city_analysis["one_time_passengers"] / city_analysis["total_trips"]

# Determine thresholds for classification
distance_threshold = city_analysis["avg_distance"].mean()
one_time_threshold = city_analysis["one_time_passenger_ratio"].mean()

# Classify cities
city_analysis["classification"] = city_analysis.apply(
    lambda row: "tourism" if (row["avg_distance"] > distance_threshold and row["one_time_passenger_ratio"] > one_time_threshold) else "business",
    axis=1
)

# Merge classification back into performance data
performance_data = pd.merge(
    fact_passenger_summary_df,
    monthly_target_trips_df,
    on=["month", "city_id"],
    how="left"
)
performance_data = pd.merge(
    performance_data,
    monthly_target_new_passengers_df,
    on=["month", "city_id"],
    how="left"
)
performance_data = pd.merge(
    performance_data,
    city_target_passenger_rating_df,
    on="city_id",
    how="left"
)
performance_data = pd.merge(
    performance_data,
    city_analysis[["city_id", "classification"]],
    on="city_id",
    how="left"
)

# Calculate metrics and trends
performance_data["trips_status"] = performance_data["total_passengers"] - performance_data["total_target_trips"]
performance_data["trips_percentage_diff"] = (
    (performance_data["total_passengers"] - performance_data["total_target_trips"]) / performance_data["total_target_trips"] * 100
)
performance_data["new_passengers_status"] = performance_data["new_passengers"] - performance_data["target_new_passengers"]
performance_data["new_passengers_percentage_diff"] = (
    (performance_data["new_passengers"] - performance_data["target_new_passengers"]) / performance_data["target_new_passengers"] * 100
)
performance_data["rating_status"] = performance_data["total_passengers"] - performance_data["target_avg_passenger_rating"]
performance_data["rating_percentage_diff"] = (
    (performance_data["total_passengers"] - performance_data["target_avg_passenger_rating"]) / performance_data["target_avg_passenger_rating"] * 100
)

# Analyze performance by classification
classification_analysis = performance_data.groupby("classification")[[
    "trips_percentage_diff",
    "new_passengers_percentage_diff",
    "rating_percentage_diff"
]].mean()

# Display results
print("City Classification:")
print(city_analysis)
print("\nMonthly Performance Against Targets:")
print(performance_data)
print("\nPerformance Trends by Classification:")
print(classification_analysis)

City Classification:
  city_id  avg_distance  total_trips  one_time_passengers  \
0    AP01     22.553938        28366                12747
1    CH01     23.518714        38981                18908
2    GJ01     10.997247        54843                11626
3    GJ02     11.517736        32026                10127
4    KA01     16.496921        16238                11681
5    KL01     24.065461        50702                26416
6    MP01     16.502473        42456                14863
7    RJ01     30.023125        76888                45856
8    TN01     14.979198        21104                 8514
9    UP01     12.512963        64299                16260

   one_time_passenger_ratio classification
0                  0.449376        tourism
1                  0.485057        tourism
2                  0.211987       business
3                  0.316212       business
4                  0.719362       business
5                  0.521005        tourism
6                  0.350080       business
7                  0.596400        tourism
8                  0.403431       business
9                  0.252881       business

Monthly Performance Against Targets:
         month city_id  new_passengers  repeat_passengers  total_passengers  \
0   2024-01-01    AP01            2513                650              3163
1   2024-01-01    CH01            3920                720              4640
2   2024-01-01    GJ01            2432               1184              3616
3   2024-01-01    GJ02            2089                544              2633
4   2024-01-01    KA01            1957                172              2129
5   2024-01-01    KL01            4865                795              5660
6   2024-01-01    MP01            2843               1033              3876
7   2024-01-01    RJ01           10423               1422             11845
8   2024-01-01    TN01            1822                392              2214
9   2024-01-01    UP01            3465               1431              4896
10  2024-02-01    AP01            2380                790              3170
11  2024-02-01    CH01            4104                853              4957
12  2024-02-01    GJ01            2254               1313              3567
13  2024-02-01    GJ02            2146                610              2756
14  2024-02-01    KA01            2107                183              2290
15  2024-02-01    KL01            4367               1005              5372
16  2024-02-01    MP01            2878               1103              3981
17  2024-02-01    RJ01           10789               1661             12450
18  2024-02-01    TN01            1647                346              1993
19  2024-02-01    UP01            3529               1659              5188
20  2024-03-01    AP01            2170                923              3093
21  2024-03-01    CH01            3228                872              4100
22  2024-03-01    GJ01            1946               1494              3440
23  2024-03-01    GJ02            1763                759              2522
24  2024-03-01    KA01            1986                208              2194
25  2024-03-01    KL01            4865               1348              6213
26  2024-03-01    MP01            2742               1091              3833
27  2024-03-01    RJ01            7417               1840              9257
28  2024-03-01    TN01            1538                427              1965
29  2024-03-01    UP01            3159               1622              4781
30  2024-04-01    AP01            1845                992              2837
31  2024-04-01    CH01            2496                789              3285
32  2024-04-01    GJ01            1843               1551              3394
33  2024-04-01    GJ02            1637                862              2499
34  2024-04-01    KA01            1836                236              2072
35  2024-04-01    KL01            4939               1576              6515
36  2024-04-01    MP01            2351               1295              3646
37  2024-04-01    RJ01            6120               1736              7856
38  2024-04-01    TN01            1242                480              1722
39  2024-04-01    UP01            2311               1496              3807
40  2024-05-01    AP01            1939                951              2890
41  2024-05-01    CH01            2730                969              3699
42  2024-05-01    GJ01            1611               1606              3217
43  2024-05-01    GJ02            1388                868              2256
44  2024-05-01    KA01            1921                349              2270
45  2024-05-01    KL01            4369               1853              6222
46  2024-05-01    MP01            2028               1563              3591
47  2024-05-01    RJ01            5332               1842              7174
48  2024-05-01    TN01            1039                504              1543
49  2024-05-01    UP01            1825               1662              3487
50  2024-06-01    AP01            1900                802              2702
51  2024-06-01    CH01            2430                867              3297
52  2024-06-01    GJ01            1540               1490              3030
53  2024-06-01    GJ02            1104                703              1807
54  2024-06-01    KA01            1874                329              2203
55  2024-06-01    KL01            3011               1049              4060
56  2024-06-01    MP01            2021               1131              3152
57  2024-06-01    RJ01            5775               1181              6956
58  2024-06-01    TN01            1226                402              1628
59  2024-06-01    UP01            1971               1727              3698

    total_target_trips  target_new_passengers  target_avg_passenger_rating  \
0                 4500                   2500                         8.50
1                 7000                   4000                         8.00
2                 9000                   2000                         7.00
3                 6000                   1800                         7.50
4                 2000                   2000                         8.50
5                 7500                   5000                         8.50
6                 7000                   2700                         8.00
7                13000                  12000                         8.25
8                 3500                   1500                         8.25
9                13000                   3200                         7.25
10                4500                   2500                         8.50
11                7000                   4000                         8.00
12                9000                   2000                         7.00
13                6000                   1800                         7.50
14                2000                   2000                         8.50
15                7500                   5000                         8.50
16                7000                   2700                         8.00
17               13000                  12000                         8.25
18                3500                   1500                         8.25
19               13000                   3200                         7.25
20                4500                   2500                         8.50
21                7000                   4000                         8.00
22                9000                   2000                         7.00
23                6000                   1800                         7.50
24                2000                   2000                         8.50
25                7500                   5000                         8.50
26                7000                   2700                         8.00
27               13000                  12000                         8.25
28                3500                   1500                         8.25
29               13000                   3200                         7.25
30                5000                   2000                         8.50
31                6000                   3000                         8.00
32               10000                   1500                         7.00
33                6500                   1500                         7.50
34                2500                   2000                         8.50
35                9000                   4000                         8.50
36                7500                   2000                         8.00
37                9500                   6000                         8.25
38                3500                   1000                         8.25
39               11000                   2000                         7.25
40                5000                   2000                         8.50
41                6000                   3000                         8.00
42               10000                   1500                         7.00
43                6500                   1500                         7.50
44                2500                   2000                         8.50
45                9000                   4000                         8.50
46                7500                   2000                         8.00
47                9500                   6000                         8.25
48                3500                   1000                         8.25
49               11000                   2000                         7.25
50                5000                   2000                         8.50
51                6000                   3000                         8.00
52               10000                   1500                         7.00
53                6500                   1500                         7.50
54                2500                   2000                         8.50
55                9000                   4000                         8.50
56                7500                   2000                         8.00
57                9500                   6000                         8.25
58                3500                   1000                         8.25
59               11000                   2000                         7.25

   classification  trips_status  trips_percentage_diff  new_passengers_status  \
0         tourism         -1337             -29.711111                     13
1         tourism         -2360             -33.714286                    -80
2        business         -5384             -59.822222                    432
3        business         -3367             -56.116667                    289
4        business           129               6.450000                    -43
5         tourism         -1840             -24.533333                   -135
6        business         -3124             -44.628571                    143
7         tourism         -1155              -8.884615                  -1577
8        business         -1286             -36.742857                    322
9        business         -8104             -62.338462                    265
10        tourism         -1330             -29.555556                   -120
11        tourism         -2043             -29.185714                    104
12       business         -5433             -60.366667                    254
13       business         -3244             -54.066667                    346
14       business           290              14.500000                    107
15        tourism         -2128             -28.373333                   -633
16       business         -3019             -43.128571                    178
17        tourism          -550              -4.230769                  -1211
18       business         -1507             -43.057143                    147
19       business         -7812             -60.092308                    329
20        tourism         -1407             -31.266667                   -330
21        tourism         -2900             -41.428571                   -772
22       business         -5560             -61.777778                    -54
23       business         -3478             -57.966667                    -37
24       business           194               9.700000                    -14
25        tourism         -1287             -17.160000                   -135
26       business         -3167             -45.242857                     42
27        tourism         -3743             -28.792308                  -4583
28       business         -1535             -43.857143                     38
29       business         -8219             -63.223077                    -41
30        tourism         -2163             -43.260000                   -155
31        tourism         -2715             -45.250000                   -504
32       business         -6606             -66.060000                    343
33       business         -4001             -61.553846                    137
34       business          -428             -17.120000                   -164
35        tourism         -2485             -27.611111                    939
36       business         -3854             -51.386667                    351
37        tourism         -1644             -17.305263                    120
38       business         -1778             -50.800000                    242
39       business         -7193             -65.390909                    311
40        tourism         -2110             -42.200000                    -61
41        tourism         -2301             -38.350000                   -270
42       business         -6783             -67.830000                    111
43       business         -4244             -65.292308                   -112
44       business          -230              -9.200000                    -79
45        tourism         -2778             -30.866667                    369
46       business         -3909             -52.120000                     28
47        tourism         -2326             -24.484211                   -668
48       business         -1957             -55.914286                     39
49       business         -7513             -68.300000                   -175
50        tourism         -2298             -45.960000                   -100
51        tourism         -2703             -45.050000                   -570
52       business         -6970             -69.700000                     40
53       business         -4693             -72.200000                   -396
54       business          -297             -11.880000                   -126
55        tourism         -4940             -54.888889                   -989
56       business         -4348             -57.973333                     21
57        tourism         -2544             -26.778947                   -225
58       business         -1872             -53.485714                    226
59       business         -7302             -66.381818                    -29

    new_passengers_percentage_diff  rating_status  rating_percentage_diff
0                         0.520000        3154.50            37111.764706
1                        -2.000000        4632.00            57900.000000
2                        21.600000        3609.00            51557.142857
3                        16.055556        2625.50            35006.666667
4                        -2.150000        2120.50            24947.058824
5                        -2.700000        5651.50            66488.235294
6                         5.296296        3868.00            48350.000000
7                       -13.141667       11836.75           143475.757576
8                        21.466667        2205.75            26736.363636
9                         8.281250        4888.75            67431.034483
10                       -4.800000        3161.50            37194.117647
11                        2.600000        4949.00            61862.500000
12                       12.700000        3560.00            50857.142857
13                       19.222222        2748.50            36646.666667
14                        5.350000        2281.50            26841.176471
15                      -12.660000        5363.50            63100.000000
16                        6.592593        3973.00            49662.500000
17                      -10.091667       12441.75           150809.090909
18                        9.800000        1984.75            24057.575758
19                       10.281250        5180.75            71458.620690
20                      -13.200000        3084.50            36288.235294
21                      -19.300000        4092.00            51150.000000
22                       -2.700000        3433.00            49042.857143
23                       -2.055556        2514.50            33526.666667
24                       -0.700000        2185.50            25711.764706
25                       -2.700000        6204.50            72994.117647
26                        1.555556        3825.00            47812.500000
27                      -38.191667        9248.75           112106.060606
28                        2.533333        1956.75            23718.181818
29                       -1.281250        4773.75            65844.827586
30                       -7.750000        2828.50            33276.470588
31                      -16.800000        3277.00            40962.500000
32                       22.866667        3387.00            48385.714286
33                        9.133333        2491.50            33220.000000
34                       -8.200000        2063.50            24276.470588
35                       23.475000        6506.50            76547.058824
36                       17.550000        3638.00            45475.000000
37                        2.000000        7847.75            95124.242424
38                       24.200000        1713.75            20772.727273
39                       15.550000        3799.75            52410.344828
40                       -3.050000        2881.50            33900.000000
41                       -9.000000        3691.00            46137.500000
42                        7.400000        3210.00            45857.142857
43                       -7.466667        2248.50            29980.000000
44                       -3.950000        2261.50            26605.882353
45                        9.225000        6213.50            73100.000000
46                        1.400000        3583.00            44787.500000
47                      -11.133333        7165.75            86857.575758
48                        3.900000        1534.75            18603.030303
49                       -8.750000        3479.75            47996.551724
50                       -5.000000        2693.50            31688.235294
51                      -19.000000        3289.00            41112.500000
52                        2.666667        3023.00            43185.714286
53                      -26.400000        1799.50            23993.333333
54                       -6.300000        2194.50            25817.647059
55                      -24.725000        4051.50            47664.705882
56                        1.050000        3144.00            39300.000000
57                       -3.750000        6947.75            84215.151515
58                       22.600000        1619.75            19633.333333
59                       -1.450000        3690.75            50906.896552

Performance Trends by Classification:
                trips_percentage_diff  new_passengers_percentage_diff  \
classification
business                   -47.899070                        5.490220
tourism                    -31.201723                       -7.548889

                rating_percentage_diff
classification

### 8. Highest and Lowest Repeat Passenger Rate (RPR%) by City and Month

Analyse the Repeat Passenger Rate (RPR%) for each city across the
six-month period. Identify the top 2 and bottom 2 cities based on their RPR% to determine which locations have the strongest and weakest rates.

Similarly, analyse the RPR% by month across all cities and identify the months with the highest and lowest repeat passenger rates. This will help to pinpoint any seasonal patterns or months with higher repeat passenger loyalty.

In [ ]:
# Calculate Repeat Passenger Rate (RPR%) for each city and month
fact_passenger_summary_df["RPR%"] = (
    fact_passenger_summary_df["repeat_passengers"] / fact_passenger_summary_df["total_passengers"] * 100
)

# Identify the top 2 and bottom 2 cities by RPR%
top_cities = fact_passenger_summary_df.groupby("city_id")["RPR%"].mean().nlargest(2).reset_index()
bottom_cities = fact_passenger_summary_df.groupby("city_id")["RPR%"].mean().nsmallest(2).reset_index()

# Analyze RPR% by month across all cities
rpr_by_month = fact_passenger_summary_df.groupby("month").agg(
    total_repeat_passengers=("repeat_passengers", "sum"),
    total_passengers=("total_passengers", "sum")
).reset_index()

rpr_by_month["RPR%"] = (
    rpr_by_month["total_repeat_passengers"] / rpr_by_month["total_passengers"] * 100
)

# Identify months with the highest and lowest RPR%
highest_month = rpr_by_month.nlargest(1, "RPR%")
lowest_month = rpr_by_month.nsmallest(1, "RPR%")

# Display results
print("Top 2 Cities by RPR%:")
print(top_cities)

print("\nBottom 2 Cities by RPR%:")
print(bottom_cities)

print("\nRPR% by Month:")
print(rpr_by_month)

print("\nMonth with Highest RPR%:")
print(highest_month)

print("\nMonth with Lowest RPR%:")
print(lowest_month)

Top 2 Cities by RPR%:
  city_id       RPR%
0    GJ01  42.963123
1    UP01  38.131873

Bottom 2 Cities by RPR%:
  city_id       RPR%
0    KA01  11.208195
1    RJ01  18.329207

RPR% by Month:
        month  total_repeat_passengers  total_passengers       RPR%
0  2024-01-01                     8343             44672  18.676128
1  2024-02-01                     9523             45724  20.827137
2  2024-03-01                    10584             41398  25.566452
3  2024-04-01                    11013             37633  29.264210
4  2024-05-01                    12167             36349  33.472723
5  2024-06-01                     9681             32533  29.757477

Month with Highest RPR%:
        month  total_repeat_passengers  total_passengers       RPR%
4  2024-05-01                    12167             36349  33.472723

Month with Lowest RPR%:
        month  total_repeat_passengers  total_passengers       RPR%
0  2024-01-01                     8343             44672  18.676128

### Further analysis and recommendations:

### 1. Factors Influencing Repeat Passenger Rates

What factors (such as quality of service, competitive pricing, or city demographics) might contribute to higher or lower repeat passenger rates in different cities? Are there correlations with socioeconomic or lifestyle patterns in these cities?

Several factors influence repeat passenger rates in ride-hailing services across different cities. Key determinants include:

1. Quality of Service

Waiting Time: Shorter waiting times enhance passenger satisfaction, leading to higher repeat usage. Conversely, longer waiting times can deter passengers from reusing the service.


Service Reliability: Consistent and dependable service fosters trust and encourages repeat patronage.

2. Pricing Strategies

Competitive Pricing: Affordable fares attract cost-sensitive passengers, increasing the likelihood of repeat usage. However, unsustainable low fares can lead to driver dissatisfaction, potentially affecting service quality.


Dynamic Pricing Models: Surge pricing during peak hours may deter repeat usage among price-sensitive customers.

3. City Demographics and Socioeconomic Factors

Income Levels: Higher-income populations are more likely to adopt and frequently use ride-hailing services.


Vehicle Ownership: Lower rates of personal vehicle ownership correlate with increased reliance on ride-hailing services.

Age Distribution: Younger individuals, particularly millennials, show a higher propensity to use and reuse ride-hailing services.


4. Built Environment and Urban Design

Neighborhood Walkability: Areas with higher walkability indices may see reduced ride-hailing usage, as residents prefer walking over short-distance rides.


Public Transit Accessibility: Easy access to public transportation can decrease dependence on ride-hailing services, affecting repeat usage rates.

5. Socioeconomic and Lifestyle Patterns

Urban vs. Suburban Areas: Urban residents with active lifestyles and higher disposable incomes are more inclined to use ride-hailing services regularly.

Cultural Attitudes: Perceptions of convenience, safety, and social status associated with ride-hailing influence repeat usage.

In summary, repeat passenger rates in ride-hailing services are shaped by a complex interplay of service quality, pricing, demographic factors, urban design, and cultural attitudes. Understanding these correlations can help service providers tailor their offerings to enhance customer retention across diverse urban landscapes.

### 2. Tourism vs. Business Demand Impact

How do tourism seasons or local events (festivals, conferences) impact Goodcabs' demand patterns? Would tailoring marketing efforts to these events increase trip volume in tourism-oriented cities?

Analyzing Goodcabs' demand patterns during tourism seasons and local events in India's tier-2 cities can provide valuable insights into how these factors influence ride-hailing services. Here's a structured approach to understanding this impact:

1. Identifying Key Events and Tourism Seasons

India's tier-2 cities host numerous festivals, conferences, and tourism seasons that significantly affect local transportation demand. For instance:

Jaipur: The Jaipur Literature Festival, typically held in January, attracts a large number of visitors.

Kochi: The Kochi-Muziris Biennale, an international exhibition of contemporary art, occurs every two years from December to March.

Ahmedabad: The International Kite Festival in January draws enthusiasts from around the world.

These events, among others, lead to increased visitor inflow, thereby impacting demand for services like Goodcabs.

2. Analyzing Demand Patterns

To assess how these events influence Goodcabs' demand:

Data Segmentation: Compare trip volumes, fare amounts, and passenger counts during event periods against non-event periods.

Key Metrics:

Trip Volume: An increase during events indicates higher demand.
Average Fare: Fluctuations may reflect changes in trip distances or surge pricing.
Passenger Types: A rise in new passengers during events suggests tourist engagement.
3. Comparative Analysis

By evaluating these metrics, you can determine the extent to which events boost demand compared to regular days. For example, a significant uptick in trip volume during the Jaipur Literature Festival would highlight the event's impact on Goodcabs' operations in Jaipur.

4. Strategic Recommendations

Understanding these patterns enables Goodcabs to tailor marketing efforts effectively:

Targeted Promotions: Offer discounts or special services during major events to attract tourists.

Resource Allocation: Deploy additional drivers in cities during peak event times to meet increased demand.

Partnerships: Collaborate with event organizers for mutual promotions, enhancing visibility among attendees.

By aligning marketing strategies with local events and tourism seasons, Goodcabs can enhance trip volumes and establish a stronger presence in tourism-oriented tier-2 cities.

### 3. Emerging Mobility Trends and Goodcabs' Adaptation

What emerging mobility trends (such as electric vehicle adoption, green energy use) are impacting the cab service market in tier-2 cities? Should Goodcabs consider integrating electric vehicles or eco-friendly initiatives to stay competitive?

Emerging mobility trends, particularly the adoption of electric vehicles (EVs) and eco-friendly initiatives, are significantly impacting the cab service market in India's tier-2 cities.

## Electric Vehicle Adoption in Tier-2 Cities

Rising EV Sales: Tier-2 cities such as Surat, Jaipur, and Nagpur have witnessed substantial growth in electric two-wheeler sales, often surpassing figures in some tier-1 cities. For instance, in 2023, Surat sold 20,150 electric two-wheelers, while Jaipur sold 18,600, exceeding sales in larger cities like Ahmedabad and Mumbai.
BUSINESS STANDARD

Government Incentives: The Indian government has introduced schemes like PM E-DRIVE, allocating substantial funds to promote EV adoption across the country, including tier-2 cities. These initiatives aim to reduce pollution and encourage the use of cleaner fuels.
REUTERS

## Eco-Friendly Initiatives in the Cab Service Market

Transition to Electric Fleets: Cab service providers are increasingly adopting electric vehicles to offer sustainable transportation options. For example, BluSmart operates an all-electric cab fleet in regions like Delhi NCR and Bengaluru, setting a precedent for eco-friendly mobility solutions.
WIKIPEDIA

Collaborations for Green Mobility: Partnerships between companies, such as the collaboration between EaseMyTrip and BluSmart, are facilitating the introduction of environment-friendly cab services, highlighting a shift towards sustainable practices in the industry.
THE CS:RUNIVERSE

## Recommendations for Goodcabs

Integrate Electric Vehicles: Given the increasing acceptance and government support for EVs in tier-2 cities, incorporating electric vehicles into Goodcabs' fleet could enhance competitiveness and align with environmental sustainability goals.

Implement Eco-Friendly Initiatives: Adopting practices such as deploying electric cabs, utilizing renewable energy for operations, and offering incentives for eco-conscious customers can position Goodcabs as a leader in sustainable urban mobility.

By embracing these emerging trends, Goodcabs can not only stay competitive but also contribute to the broader goal of promoting clean and sustainable transportation solutions in India's growing urban centers.

## 4. Partnership Opportunities with Local Businesses

Are there opportunities for Goodcabs to partner with local businesses (such as hotels, malls, or event venues) to boost demand and improve customer loyalty?
Could these partnerships drive more traffic, especially in tourism-heavy or high-footfall areas?

Goodcabs has a significant opportunity to collaborate with local businesses in tier-2 cities to enhance its services and customer loyalty. Examples include:

Potential Partnerships
Hotels and Resorts: Partner with hotels to provide exclusive cab services for their guests, such as airport transfers or city tours. For example, partnering with luxury resorts during peak tourism seasons could guarantee a steady demand for premium cabs.

Shopping Malls: Establish designated pickup/drop-off points at high-footfall areas like malls. Offering discounts on rides for mall customers during events or sales could attract more passengers.

Event Venues: Collaborate with venues hosting weddings, conferences, or festivals to ensure reliable transportation for attendees.

Impact of Partnerships
Boost in Trip Volume: Targeted partnerships could lead to an increase in ride requests, especially during peak business hours or events.

Enhanced Customer Loyalty: Partnering with reputed businesses can position Goodcabs as a trusted and premium service provider, improving customer retention.

Actionable Strategies
Offer co-branded promotional offers (e.g., ride discounts for guests booking a stay at a partner hotel).
Implement a loyalty program that rewards passengers for frequent rides linked to partner businesses.

## 5. Data Collection for Enhanced Data-Driven Decisions

To make Goodcabs more data-driven and improve its performance across key metrics (such as repeat passenger rate, customer satisfaction, new passengers, and trip volume), what additional data should Goodcabs collect?
Consider data that could provide deeper insights into customer behavior, operational efficiency, and market trends.

Data Collection for Enhanced Data-Driven Decisions
To improve its performance and become more data-driven, Goodcabs should focus on collecting additional data points that provide deeper insights into customer behavior, operational efficiency, and market trends.

Additional Data to Collect
Customer Feedback Data:

Detailed passenger feedback on drivers, vehicle cleanliness, ride quality, and punctuality.
Suggestions for improvement to enhance customer satisfaction.
Trip-Specific Data:

Preferred pickup and drop-off locations to identify high-demand zones.
Average waiting time for passengers and response time for drivers.
Driver Performance Metrics:

Ratings given by passengers to drivers.
Frequency of on-time trips and cancellation rates by drivers.
Seasonal Trends:

Seasonal demand fluctuations, such as during festivals, public holidays, or school vacations.
Analysis of ride patterns (weekday vs. weekend rides).
Customer Demographics:

Passenger age group, profession, and preferences (e.g., eco-friendly vehicles or premium cabs).
Benefits of Collecting Additional Data
Improved Customer Retention: By understanding passenger preferences and addressing their concerns, Goodcabs can enhance the overall customer experience.

Operational Efficiency: Analyzing driver performance and high-demand areas can help optimize resource allocation.

Market Trends: Identifying patterns in customer behavior and seasonal trends enables more targeted marketing and promotions.

Next Steps for Goodcabs
Invest in technology to collect, analyze, and visualize data (e.g., dashboards for real-time insights).
Implement machine learning models to predict demand based on historical trends and external factors (e.g., weather, events).
Use insights to inform business decisions, such as expanding services to underserved areas or adding features to the app for a seamless booking experience.